version: '2'
services:
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ~/Documents/Database/mysql_data/5.7:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=potato
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - DEFAULT_AUTH=mysql_native_password
    ports:
      - "8082:3306"